# Generated by Django 4.1.7 on 2023-06-23 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dell', '0006_alter_registrationform_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=78)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=40, null=True)),
                ('prize', models.IntegerField(default='', null=True)),
                ('productid', models.CharField(max_length=60, null=True)),
                ('pub_date', models.DateField(max_length=78, null=True)),
                ('image', models.ImageField(default='', null=True, upload_to='static/uploadimage')),
            ],
        ),
    ]
