# Generated by Django 4.1.7 on 2023-06-23 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dell', '0007_details_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prize',
            field=models.IntegerField(default='0', null=True),
        ),
    ]
